language: node_js
sudo: false

node_js:
  - "10"
  - "12"
  - "13"

cache:
  npm: false

install:
  - "npm install --ignore-scripts"
  - "npx allow-scripts"

#@todo uncomment before v1
#jobs:
#  include:
#    - stage: release
#      if: branch = master AND type = push
#      node_js: "12"
#      deploy:
#        provider: "script"
#        skip_cleanup: true
#        script:
#          - "npx semantic-release"
