name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
    with:
      post-checkout-steps: |
        - name: Set git user to avoid warnings
          shell: bash
          run: |
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
